[functions.plaza-cleanup-expired]
verify_jwt = false

[functions.market-stripe-connect]
verify_jwt = true

[functions.market-create-checkout]
verify_jwt = true

[functions.market-stripe-webhook]
verify_jwt = false

[functions.market-stripe-payout]
verify_jwt = false

[functions.market-download]
verify_jwt = true

[functions.market-public-preview]
verify_jwt = false

[functions.market-reconcile-purchase]
enabled = true
verify_jwt = true
import_map = "./functions/market-reconcile-purchase/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/market-reconcile-purchase/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/market-reconcile-purchase/*.html" ]
