/** Central, stable error vocabulary for the FP-005 boundary. */
export const FP005_ERROR_CODES = Object.freeze({
  STORAGE_PLACEMENT_INVALID: "FP005_STORAGE_PLACEMENT_INVALID",
  STORAGE_LOCATOR_INVALID: "FP005_STORAGE_LOCATOR_INVALID",
  TENANT_SCOPE_DENIED: "FP005_TENANT_SCOPE_DENIED",
  AUTHORIZATION_REQUIRED: "FP005_AUTHORIZATION_REQUIRED",
  INPUT_INVALID: "FP005_INPUT_INVALID",
  INPUT_TOO_LARGE: "FP005_INPUT_TOO_LARGE",
  PATH_INVALID: "FP005_PATH_INVALID",
  ARCHIVE_INVALID: "FP005_ARCHIVE_INVALID",
  ACTIVE_CONTENT_REJECTED: "FP005_ACTIVE_CONTENT_REJECTED",
  RAW_BLOB_REJECTED: "FP005_RAW_BLOB_REJECTED",
  REDACTION_REQUIRED: "FP005_REDACTION_REQUIRED",
  TELEMETRY_INVALID: "FP005_TELEMETRY_INVALID",
  QUOTA_EXCEEDED: "FP005_QUOTA_EXCEEDED",
  RETENTION_PROTECTED: "FP005_RETENTION_PROTECTED",
  SCHEMA_UNSUPPORTED: "FP005_SCHEMA_UNSUPPORTED",
} as const);

export type Fp005ErrorCode = typeof FP005_ERROR_CODES[keyof typeof FP005_ERROR_CODES];
