import { normalizeGlobeCell } from "./globe-cell.ts";

function assertEquals(actual: unknown, expected: unknown) {
  if (JSON.stringify(actual) !== JSON.stringify(expected)) {
    throw new Error(`Expected ${JSON.stringify(expected)}, received ${JSON.stringify(actual)}`);
  }
}

Deno.test("accepts exact cells generated by the browser grid", () => {
  assertEquals(normalizeGlobeCell({ id: "globe:v11-meridian-parallel-quarter-degree:217:1065", version: "v11-meridian-parallel-quarter-degree", band: 217, column: 1065 }), {
    id: "globe:v11-meridian-parallel-quarter-degree:217:1065", version: "v11-meridian-parallel-quarter-degree", band: 217, column: 1065
  });
});

Deno.test("rejects mismatched, out-of-band and impossible columns", () => {
  assertEquals(normalizeGlobeCell({ id: "globe:v11-meridian-parallel-quarter-degree:217:1", version: "wrong", band: 217, column: 1 }), null);
  assertEquals(normalizeGlobeCell({ id: "globe:v11-meridian-parallel-quarter-degree:720:1", version: "v11-meridian-parallel-quarter-degree", band: 720, column: 1 }), null);
  assertEquals(normalizeGlobeCell({ id: "globe:v11-meridian-parallel-quarter-degree:0:999", version: "v11-meridian-parallel-quarter-degree", band: 0, column: 999 }), null);
  assertEquals(normalizeGlobeCell({ id: "globe:v11-meridian-parallel-quarter-degree:217:2", version: "v11-meridian-parallel-quarter-degree", band: 217, column: 1 }), null);
});
