function assert(condition: unknown, message = "assertion failed"): asserts condition { if (!condition) throw new Error(message); }
function assertFalse(condition: unknown, message = "expected false"): void { assert(!condition, message); }
function assertEquals<T>(actual: T, expected: T, message = "values differ"): void { assert(Object.is(actual, expected), `${message}: ${String(actual)} !== ${String(expected)}`); }
import { asAssetId, asAssetRevisionId, asBehaviorId, asComponentId, asDependencyId, asEntityId, asOwnerId, asProjectId, asRevisionId, asSceneId, asSha256, compileNoCodeBehavior, createGameProject, type CallerContext, type GameProjectDraft } from "../../src/game/game-300/core.ts";
import { applyPreviewUpdate, createIntegratedPackage, createPreviewState, resolveAssetBinding, rollbackPreview, type AssetBinding, type CanonicalAssetRevision, type DependencyLock, type LicenseSnapshot } from "../../src/game/game-340/core.ts";

const owner = asOwnerId("owner-game-340"); const projectId = asProjectId("project-game-340"); const revisionId = asRevisionId("revision-game-340-1");
const caller: CallerContext = { projectId, ownerId: owner, revisionId }; const drawHash = asSha256("a".repeat(64)); const audioHash = asSha256("b".repeat(64)); const depHash = asSha256("c".repeat(64));
async function fixture() {
  const behavior = compileNoCodeBehavior({ behaviorId: asBehaviorId("behavior-340"), rules: [] });
  const draft: GameProjectDraft = { schemaVersion: 1, projectId, ownerId: owner, name: "GAME-340", revision: { revisionId, projectId, ownerId: owner, sequence: 1 }, scenes: [{ sceneId: asSceneId("scene-340"), name: "Main", rootEntityIds: [asEntityId("entity-340")], entities: [{ entityId: asEntityId("entity-340"), name: "Player", components: [
    { type: "TRANSFORM", componentId: asComponentId("transform-340"), x: 0, y: 0, rotation: 0, scaleX: 1, scaleY: 1 },
    { type: "SPRITE", componentId: asComponentId("draw-component-340"), asset: { kind: "DRAW", assetId: asAssetId("draw-340"), revisionId: asAssetRevisionId("draw-rev-1"), ownerId: owner, contentHash: drawHash, mode: "LIVE" }, visible: true },
    { type: "AUDIO_SOURCE", componentId: asComponentId("audio-component-340"), asset: { kind: "AUDIO", assetId: asAssetId("audio-340"), revisionId: asAssetRevisionId("audio-rev-1"), ownerId: owner, contentHash: audioHash, mode: "PINNED" }, loop: true, volume: 0.5 },
    { type: "BEHAVIOR", componentId: asComponentId("behavior-component-340"), behaviorId: behavior.behaviorId },
  ] }] }], prefabs: [], dependencies: [{ dependencyId: asDependencyId("dep-340"), kind: "PACKAGE", ownerId: owner, ownerRevisionId: revisionId, targetId: "runtime", targetRevisionId: "runtime-1", dependsOn: [] }], behaviors: [behavior] };
  const project = await createGameProject(draft, caller);
  const authority: CanonicalAssetRevision[] = [
    { projectId: String(projectId), ownerId: String(owner), kind: "DRAW", assetId: "draw-340", revisionId: "draw-rev-1", contentHash: drawHash, licenseId: "license-draw", permission: "PREVIEW", reviewStatus: "APPROVED" },
    { projectId: String(projectId), ownerId: String(owner), kind: "AUDIO", assetId: "audio-340", revisionId: "audio-rev-1", contentHash: audioHash, licenseId: "license-audio", permission: "PREVIEW", reviewStatus: "APPROVED" },
  ];
  const bindings: AssetBinding[] = [
    { componentId: "draw-component-340", projectId: String(projectId), ownerId: String(owner), kind: "DRAW", assetId: "draw-340", mode: "LIVE", licenseId: "license-draw", permission: "PREVIEW" },
    { componentId: "audio-component-340", projectId: String(projectId), ownerId: String(owner), kind: "AUDIO", assetId: "audio-340", mode: "PINNED", revisionId: "audio-rev-1", licenseId: "license-audio", permission: "PREVIEW" },
  ];
  const dependencies: DependencyLock[] = [{ dependencyId: "dep-340", targetId: "runtime", targetRevisionId: "runtime-1", contentHash: depHash, licenseId: "license-runtime", dependsOn: [] }];
  const licenses: LicenseSnapshot[] = [
    { licenseId: "license-draw", ownerId: String(owner), scope: "PACKAGE", revisionId: String(revisionId) }, { licenseId: "license-audio", ownerId: String(owner), scope: "PACKAGE", revisionId: String(revisionId) }, { licenseId: "license-runtime", ownerId: String(owner), scope: "PACKAGE", revisionId: String(revisionId) },
  ];
  return { project, authority, bindings, dependencies, licenses };
}

Deno.test("GAME340-SCOPE-001 resolves LIVE and PINNED without source mutation", async () => { const f = await fixture(); const before = JSON.stringify(f.project); const live = resolveAssetBinding(f.bindings[0]!, f.authority, caller); const pinned = resolveAssetBinding(f.bindings[1]!, f.authority, caller); assert(live.ok && pinned.ok); assertEquals(live.value!.revisionId, "draw-rev-1"); assertEquals(pinned.value!.revisionId, "audio-rev-1"); assertEquals(JSON.stringify(f.project), before); });
Deno.test("GAME340-EVIDENCE-001 creates deterministic package and preview updates", async () => { const f = await fixture(); const one = await createIntegratedPackage(f.project, caller, f.bindings, f.authority, f.dependencies, f.licenses); const two = await createIntegratedPackage(f.project, caller, f.bindings.slice().reverse(), f.authority, f.dependencies, f.licenses); assert(one.ok && two.ok); assertEquals(one.value!.packageHash, two.value!.packageHash); const initial = createPreviewState(one.value!, { projectId: String(projectId), ownerId: String(owner), revisionId: String(revisionId) }); assert(initial.ok); const update = await applyPreviewUpdate(initial.value!, { eventId: "draw-event-1", sequence: 1, projectId: String(projectId), ownerId: String(owner), projectRevisionId: String(revisionId), kind: "DRAW", assetId: "draw-340", revisionId: "draw-rev-2", contentHash: asSha256("d".repeat(64)) }); assert(update.ok); assertEquals(update.value!.updates.length, 1); assertEquals(rollbackPreview(update.value!).updates.length, 0); });
Deno.test("GAME340-SCOPE-001 stale, wrong, duplicate, cycle, and locked claims fail closed", async () => { const f = await fixture(); assertFalse(resolveAssetBinding({ ...f.bindings[0]!, revisionId: "caller-revision", contentHash: drawHash }, f.authority, caller).ok); assertFalse((await createIntegratedPackage(f.project, { ...caller, ownerId: asOwnerId("wrong-owner") }, f.bindings, f.authority, f.dependencies, f.licenses)).ok); const cycle = [{ ...f.dependencies[0]!, dependsOn: ["dep-340"] }]; assertFalse((await createIntegratedPackage(f.project, caller, f.bindings, f.authority, cycle, f.licenses)).ok); const packageResult = await createIntegratedPackage(f.project, caller, f.bindings, f.authority, f.dependencies, f.licenses); const initial = createPreviewState(packageResult.value!, { projectId: String(projectId), ownerId: String(owner), revisionId: String(revisionId) }).value!; const pinned = await applyPreviewUpdate(initial, { eventId: "audio-event-1", sequence: 1, projectId: String(projectId), ownerId: String(owner), projectRevisionId: String(revisionId), kind: "AUDIO", assetId: "audio-340", revisionId: "audio-rev-2", contentHash: asSha256("e".repeat(64)) }); assertFalse(pinned.ok); const draw = { eventId: "draw-event-1", sequence: 1, projectId: String(projectId), ownerId: String(owner), projectRevisionId: String(revisionId), kind: "DRAW" as const, assetId: "draw-340", revisionId: "draw-rev-2", contentHash: asSha256("d".repeat(64)) }; const applied = await applyPreviewUpdate(initial, draw); assert(applied.ok); assertFalse((await applyPreviewUpdate(applied.value!, draw)).ok); });
Deno.test("GAME340-STOP-001 remains host-neutral", async () => { const source = await Deno.readTextFile("src/game/game-340/core.ts"); assertFalse(/document|fetch|WebSocket|localStorage|indexedDB|Deno\.write|Deno\.read/u.test(source)); });
