import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { buildPortableRelease } from '../../scripts/build-portable-release.mjs';

async function fixture(t, valid = true) {
  const scratch = await mkdtemp(join(tmpdir(), 'pixieed-portable-release-'));
  t.after(() => rm(scratch, { recursive: true, force: true }));
  const root = join(scratch, 'source');
  await mkdir(root);
  execFileSync('git', ['init', '-q', root]);
  const entries = {
    'index.html': '<h1>site</h1>',
    'assets/test.bin': 'asset',
    'data/site-config.js': 'export const publicConfig = true;',
    'supabase/private.sql': 'private',
    'tests/private.html': 'fixture',
    'docs/notes.html': 'notes',
    'books/index.html': 'unpublished',
    'scripts/generate-puzzle-ogp-pages.mjs': `import { mkdir, writeFile } from 'node:fs/promises';\nimport { join } from 'node:path';\nfor (const game of ['spot-difference','hidden-object']) { const dir=join(process.cwd(),'play',game,'puzzles'); await mkdir(join(dir,'22222222-2222-4222-8222-222222222222'),{recursive:true}); await writeFile(join(dir,'.pixieed-generated-puzzle-share-pages'),'Generated by scripts/generate-puzzle-ogp-pages.mjs\\n'); await writeFile(join(dir,'22222222-2222-4222-8222-222222222222','index.html'),'<meta>'); await writeFile(join(dir,'22222222-2222-4222-8222-222222222222','ogp-1234567890abcdef.png'),'PNG'); }`,
  };
  for (const [name, value] of Object.entries(entries)) {
    await mkdir(join(root, name, '..'), { recursive: true });
    await writeFile(join(root, name), value);
  }
  execFileSync('git', ['add', '.'], { cwd: root });
  execFileSync('git', ['-c', 'user.name=Fixture', '-c', 'user.email=fixture@example.invalid', 'commit', '-qm', 'fixture'], { cwd: root });
  await writeFile(join(root, 'index.html'), '<h1>working tree edit</h1>');
  await writeFile(join(root, 'untracked.html'), 'must not ship');
  if (valid) {
    for (const game of ['spot-difference', 'hidden-object']) {
      const page = join(root, 'play', game, 'puzzles', '22222222-2222-4222-8222-222222222222');
      await mkdir(page, { recursive: true });
      await writeFile(join(page, '..', '.pixieed-generated-puzzle-share-pages'), 'Generated by scripts/generate-puzzle-ogp-pages.mjs\n');
      await writeFile(join(page, 'index.html'), '<meta>');
      await writeFile(join(page, 'ogp-1234567890abcdef.png'), 'PNG');
    }
  }
  return { root, scratch };
}

test('portable release reuses marked puzzle output, packages site at ZIP root, and keeps manifest outside ZIP', async t => {
  const { root, scratch } = await fixture(t);
  const output = join(scratch, 'release');
  const result = await buildPortableRelease({ root, output, reusePuzzles: true });
  assert.equal(result.puzzleMode, 'reuse');
  assert.equal(result.puzzlePages, 2);
  const manifest = JSON.parse(await readFile(result.manifest, 'utf8'));
  assert.equal(manifest.trackedDirty, true);
  assert.equal(manifest.puzzleMode, 'reuse');
  assert.match(manifest.puzzleModeNote, /may not be reflected/);
  assert.equal(manifest.puzzlePages, 2);
  assert.ok(manifest.zipSha256.match(/^[a-f0-9]{64}$/));
  assert.ok(manifest.files.some(file => file.path === '.nojekyll'));
  const listing = execFileSync('unzip', ['-Z1', result.zip], { encoding: 'utf8' }).trim().split('\n');
  assert.ok(listing.includes('index.html'));
  assert.ok(listing.includes('.nojekyll'));
  assert.ok(!listing.some(path => path.startsWith('site/')));
  assert.ok(!listing.some(path => /(?:release\.json|supabase\/|tests\/|docs\/|books\/|untracked\.html)/.test(path)));
  assert.equal(await readFile(join(output, 'site/index.html'), 'utf8'), '<h1>working tree edit</h1>');
});

test('portable release refreshes puzzle pages before packaging by default', async t => {
  const { root, scratch } = await fixture(t, false);
  const output = join(scratch, 'release');
  const result = await buildPortableRelease({ root, output });
  assert.equal(result.puzzleMode, 'refresh');
  assert.equal(result.puzzlePages, 2);
  const manifest = JSON.parse(await readFile(result.manifest, 'utf8'));
  assert.equal(manifest.puzzleMode, 'refresh');
  assert.equal(manifest.puzzlePages, 2);
  const page = 'play/hidden-object/puzzles/22222222-2222-4222-8222-222222222222';
  assert.equal(await readFile(join(output, 'site', page, 'index.html'), 'utf8'), '<meta>');
  assert.ok((await readFile(join(output, 'site', page, 'ogp-1234567890abcdef.png'))).length > 0);
});

test('refresh failure does not package or fall back to saved puzzle pages', async t => {
  const { root, scratch } = await fixture(t);
  const output = join(scratch, 'release');
  await writeFile(join(root, 'scripts/generate-puzzle-ogp-pages.mjs'), 'process.exit(1);');
  const saved = join(root, 'play/hidden-object/puzzles/22222222-2222-4222-8222-222222222222/index.html');
  assert.equal(await readFile(saved, 'utf8'), '<meta>');
  await assert.rejects(buildPortableRelease({ root, output }), /failed|status|exit/i);
  await assert.rejects(readFile(output), { code: 'ENOENT' });
  assert.equal(await readFile(saved, 'utf8'), '<meta>');
});

test('portable release refuses missing saved puzzle output and never overwrites output', async t => {
  const { root, scratch } = await fixture(t, false);
  const output = join(scratch, 'release');
  await assert.rejects(buildPortableRelease({ root, output, reusePuzzles: true }), /Missing generated puzzle directory/);
  await assert.rejects(readFile(output), { code: 'ENOENT' });
  await mkdir(output);
  await writeFile(join(output, 'keep.txt'), 'keep');
  await assert.rejects(buildPortableRelease({ root, output, reusePuzzles: true }), /already exists/);
  assert.equal(await readFile(join(output, 'keep.txt'), 'utf8'), 'keep');
});

test('portable release rejects incomplete OGP and output paths inside or above source', async t => {
  const { root, scratch } = await fixture(t);
  const missingImage = join(root, 'play/hidden-object/puzzles/22222222-2222-4222-8222-222222222222/ogp-1234567890abcdef.png');
  await rm(missingImage);
  await assert.rejects(buildPortableRelease({ root, output: join(scratch, 'missing-ogp'), reusePuzzles: true }), /OGP image is missing/);
  await assert.rejects(buildPortableRelease({ root, output: join(root, 'nested-release'), reusePuzzles: true }), /outside/);
  await assert.rejects(buildPortableRelease({ root, output: scratch, reusePuzzles: true }), /outside/);
  const alias = join(scratch, 'source-alias');
  await symlink(root, alias);
  await assert.rejects(buildPortableRelease({ root, output: join(alias, 'release'), reusePuzzles: true }), /outside/);
});
