-- Site-wide advertising suppression is a standalone presentation entitlement.
-- It does not grant market review, DEV, seller, purchase, or download access.

create table if not exists public.site_ad_free_grants (
  user_id uuid primary key references auth.users(id) on delete cascade,
  active boolean not null default true,
  granted_by uuid not null references auth.users(id) on delete restrict,
  granted_at timestamptz not null default timezone('utc', now()),
  revoked_by uuid references auth.users(id) on delete restrict,
  revoked_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  check (
    (active and revoked_by is null and revoked_at is null)
    or (not active and revoked_by is not null and revoked_at is not null)
  )
);

alter table public.site_ad_free_grants enable row level security;
revoke all on public.site_ad_free_grants from public, anon, authenticated;

create table if not exists public.site_ad_free_grant_audit (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  enabled boolean not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.site_ad_free_grant_audit enable row level security;
revoke all on public.site_ad_free_grant_audit from public, anon, authenticated;
create index if not exists site_ad_free_grant_audit_created_idx
  on public.site_ad_free_grant_audit (created_at desc);

create or replace function public.site_current_user_ad_free()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select auth.uid() is not null and exists (
    select 1
    from public.site_ad_free_grants as grants
    where grants.user_id = auth.uid()
      and grants.active
  );
$$;

create or replace function public.site_admin_list_ad_free_grants()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.market_current_user_is_admin() then
    raise exception 'admin permission required';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'user_id', grants.user_id,
      'email', users.email,
      'granted_at', grants.granted_at,
      'updated_at', grants.updated_at
    ) order by grants.updated_at desc)
    from public.site_ad_free_grants as grants
    join auth.users as users on users.id = grants.user_id
    where grants.active
  ), '[]'::jsonb);
end;
$$;

create or replace function public.site_admin_set_ad_free_by_email(
  input_email text,
  input_enabled boolean
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_user_id uuid := auth.uid();
  v_email text := lower(trim(coalesce(input_email, '')));
  v_target_user auth.users%rowtype;
  v_now timestamptz := timezone('utc', now());
begin
  if not public.market_current_user_is_admin() then
    raise exception 'admin permission required';
  end if;
  if v_email = '' or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'valid email required';
  end if;

  select * into v_target_user
  from auth.users as users
  where lower(users.email) = v_email
  limit 1;

  if not found or v_target_user.email_confirmed_at is null then
    raise exception 'confirmed account not found';
  end if;
  if v_target_user.id = v_actor_user_id then
    raise exception 'admin self grant is not allowed';
  end if;

  insert into public.site_ad_free_grants (
    user_id,
    active,
    granted_by,
    granted_at,
    revoked_by,
    revoked_at,
    updated_at
  ) values (
    v_target_user.id,
    input_enabled,
    v_actor_user_id,
    v_now,
    case when input_enabled then null else v_actor_user_id end,
    case when input_enabled then null else v_now end,
    v_now
  )
  on conflict (user_id) do update set
    active = excluded.active,
    granted_by = case
      when excluded.active then excluded.granted_by
      else public.site_ad_free_grants.granted_by
    end,
    granted_at = case
      when excluded.active then excluded.granted_at
      else public.site_ad_free_grants.granted_at
    end,
    revoked_by = excluded.revoked_by,
    revoked_at = excluded.revoked_at,
    updated_at = excluded.updated_at;

  insert into public.site_ad_free_grant_audit (
    actor_user_id,
    target_user_id,
    enabled
  ) values (
    v_actor_user_id,
    v_target_user.id,
    input_enabled
  );

  return jsonb_build_object(
    'user_id', v_target_user.id,
    'email', v_target_user.email,
    'enabled', input_enabled,
    'updated_at', v_now
  );
end;
$$;

revoke all on function public.site_current_user_ad_free() from public, anon, authenticated;
revoke all on function public.site_admin_list_ad_free_grants() from public, anon, authenticated;
revoke all on function public.site_admin_set_ad_free_by_email(text, boolean) from public, anon, authenticated;
grant execute on function public.site_current_user_ad_free() to authenticated;
grant execute on function public.site_admin_list_ad_free_grants() to authenticated;
grant execute on function public.site_admin_set_ad_free_by_email(text, boolean) to authenticated;
