-- Monthly Stripe Connect transfers. Amounts below one yen and below the
-- configured payout minimum remain in the internal micro-yen ledger.

alter table public.market_royalty_ledger
  add column if not exists paid_microyen bigint not null default 0;

alter table public.market_royalty_ledger
  drop constraint if exists market_royalty_paid_microyen_check;
alter table public.market_royalty_ledger
  add constraint market_royalty_paid_microyen_check
  check (paid_microyen >= 0 and paid_microyen <= amount_microyen);

create table if not exists public.market_payout_batches (
  id uuid primary key default gen_random_uuid(),
  recipient_user_id uuid not null references auth.users(id) on delete restrict,
  provider text not null default 'stripe' check (provider = 'stripe'),
  provider_account_id text not null,
  currency text not null default 'jpy' check (currency = 'jpy'),
  amount_yen integer not null check (amount_yen > 0),
  amount_microyen bigint not null check (amount_microyen > 0),
  status text not null default 'prepared'
    check (status in ('prepared', 'transferred', 'partially_reversed', 'reversed', 'failed')),
  provider_transfer_id text unique,
  reversed_yen integer not null default 0 check (reversed_yen >= 0),
  failure_message text not null default '',
  prepared_at timestamptz not null default timezone('utc', now()),
  transferred_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  check (amount_microyen = amount_yen::bigint * 1000000),
  check (reversed_yen <= amount_yen)
);

create unique index if not exists market_payout_one_prepared_per_recipient
  on public.market_payout_batches(recipient_user_id)
  where status = 'prepared';
create index if not exists market_payout_recipient_history_idx
  on public.market_payout_batches(recipient_user_id, prepared_at desc);

create table if not exists public.market_payout_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.market_payout_batches(id) on delete restrict,
  royalty_ledger_id uuid not null references public.market_royalty_ledger(id) on delete restrict,
  purchase_id uuid not null references public.market_purchases(id) on delete restrict,
  amount_microyen bigint not null check (amount_microyen > 0),
  reversed_microyen bigint not null default 0 check (reversed_microyen >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (batch_id, royalty_ledger_id),
  check (reversed_microyen <= amount_microyen)
);

create index if not exists market_payout_items_purchase_idx
  on public.market_payout_items(purchase_id, batch_id);

alter table public.market_payout_batches enable row level security;
alter table public.market_payout_items enable row level security;

create policy market_payout_batches_read_own
on public.market_payout_batches for select
to authenticated
using (recipient_user_id = auth.uid());

create policy market_payout_items_read_own
on public.market_payout_items for select
to authenticated
using (
  exists (
    select 1 from public.market_payout_batches batch
    where batch.id = batch_id and batch.recipient_user_id = auth.uid()
  )
);

create or replace function public.market_next_stripe_payout_batch_v1(
  input_minimum_yen integer default 5000
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch public.market_payout_batches%rowtype;
  v_recipient uuid;
  v_account_id text;
  v_total_microyen bigint;
  v_transfer_microyen bigint;
  v_remaining bigint;
  v_ledger record;
  v_allocation bigint;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required';
  end if;
  if input_minimum_yen < 1 or input_minimum_yen > 10000000 then
    raise exception 'invalid payout minimum';
  end if;

  update public.market_royalty_ledger
  set status = 'available'
  where status = 'pending'
    and available_at <= timezone('utc', now())
    and paid_microyen < amount_microyen;

  select * into v_batch
  from public.market_payout_batches
  where status = 'prepared'
  order by prepared_at
  limit 1
  for update skip locked;
  if found then
    return jsonb_build_object(
      'batch_id', v_batch.id,
      'recipient_user_id', v_batch.recipient_user_id,
      'provider_account_id', v_batch.provider_account_id,
      'amount_yen', v_batch.amount_yen,
      'currency', v_batch.currency
    );
  end if;

  select ledger.recipient_user_id, payout.provider_account_id,
    sum(ledger.amount_microyen - ledger.paid_microyen)::bigint
  into v_recipient, v_account_id, v_total_microyen
  from public.market_royalty_ledger ledger
  join public.market_seller_payout_accounts payout
    on payout.user_id = ledger.recipient_user_id
   and payout.provider = 'stripe'
   and payout.onboarding_status = 'verified'
   and payout.payouts_enabled
  where ledger.status = 'available'
    and ledger.paid_microyen < ledger.amount_microyen
  group by ledger.recipient_user_id, payout.provider_account_id
  having sum(ledger.amount_microyen - ledger.paid_microyen) >= input_minimum_yen::bigint * 1000000
  order by min(ledger.available_at), ledger.recipient_user_id
  limit 1;

  if v_recipient is null then
    return null;
  end if;

  v_transfer_microyen := floor(v_total_microyen::numeric / 1000000)::bigint * 1000000;
  insert into public.market_payout_batches (
    recipient_user_id, provider_account_id, amount_yen, amount_microyen
  ) values (
    v_recipient, v_account_id, (v_transfer_microyen / 1000000)::integer, v_transfer_microyen
  ) returning * into v_batch;

  v_remaining := v_transfer_microyen;
  for v_ledger in
    select id, purchase_id, amount_microyen, paid_microyen
    from public.market_royalty_ledger
    where recipient_user_id = v_recipient
      and status = 'available'
      and paid_microyen < amount_microyen
    order by available_at, created_at, id
    for update
  loop
    exit when v_remaining <= 0;
    v_allocation := least(v_remaining, v_ledger.amount_microyen - v_ledger.paid_microyen);
    insert into public.market_payout_items(batch_id, royalty_ledger_id, purchase_id, amount_microyen)
    values (v_batch.id, v_ledger.id, v_ledger.purchase_id, v_allocation);
    v_remaining := v_remaining - v_allocation;
  end loop;

  if v_remaining <> 0 then
    raise exception 'payout allocation did not balance';
  end if;

  return jsonb_build_object(
    'batch_id', v_batch.id,
    'recipient_user_id', v_batch.recipient_user_id,
    'provider_account_id', v_batch.provider_account_id,
    'amount_yen', v_batch.amount_yen,
    'currency', v_batch.currency
  );
end;
$$;

revoke all on function public.market_next_stripe_payout_batch_v1(integer)
  from public, anon, authenticated;
grant execute on function public.market_next_stripe_payout_batch_v1(integer)
  to service_role;

create or replace function public.market_finalize_stripe_payout_batch_v1(
  input_batch_id uuid,
  input_transfer_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_batch public.market_payout_batches%rowtype;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required';
  end if;
  select * into v_batch
  from public.market_payout_batches
  where id = input_batch_id
  for update;
  if not found then raise exception 'payout batch not found'; end if;
  if v_batch.status = 'transferred' and v_batch.provider_transfer_id = btrim(input_transfer_id) then return; end if;
  if v_batch.status <> 'prepared' then raise exception 'payout batch is not prepared'; end if;

  update public.market_royalty_ledger ledger
  set paid_microyen = ledger.paid_microyen + allocations.amount_microyen,
      status = case
        when ledger.paid_microyen + allocations.amount_microyen >= ledger.amount_microyen then 'paid_out'
        else 'available'
      end
  from (
    select royalty_ledger_id, sum(amount_microyen)::bigint as amount_microyen
    from public.market_payout_items
    where batch_id = input_batch_id
    group by royalty_ledger_id
  ) allocations
  where ledger.id = allocations.royalty_ledger_id;

  update public.market_payout_batches
  set status = 'transferred',
      provider_transfer_id = btrim(input_transfer_id),
      transferred_at = timezone('utc', now()),
      updated_at = timezone('utc', now())
  where id = input_batch_id;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id, details)
  values (
    null, 'stripe_payout_transferred', 'market_payout_batch', input_batch_id::text,
    jsonb_build_object('transfer_id', input_transfer_id, 'amount_yen', v_batch.amount_yen)
  );
end;
$$;

revoke all on function public.market_finalize_stripe_payout_batch_v1(uuid, text)
  from public, anon, authenticated;
grant execute on function public.market_finalize_stripe_payout_batch_v1(uuid, text)
  to service_role;

create or replace function public.market_record_stripe_transfer_reversal_v1(
  input_payout_item_id bigint,
  input_reversed_yen integer,
  input_reversal_id text,
  input_event_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_item public.market_payout_items%rowtype;
  v_batch public.market_payout_batches%rowtype;
  v_microyen bigint := input_reversed_yen::bigint * 1000000;
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required';
  end if;
  if input_reversed_yen <= 0 then raise exception 'positive reversal amount required'; end if;

  select * into v_item
  from public.market_payout_items
  where id = input_payout_item_id
  for update;
  if not found or v_item.reversed_microyen + v_microyen > v_item.amount_microyen then
    raise exception 'invalid payout item reversal';
  end if;
  select * into v_batch
  from public.market_payout_batches
  where id = v_item.batch_id
  for update;
  if not found or v_batch.status not in ('transferred', 'partially_reversed') then
    raise exception 'transferred payout batch required';
  end if;

  update public.market_payout_items
  set reversed_microyen = reversed_microyen + v_microyen
  where id = v_item.id;
  update public.market_payout_batches
  set reversed_yen = reversed_yen + input_reversed_yen,
      status = case when reversed_yen + input_reversed_yen >= amount_yen then 'reversed' else 'partially_reversed' end,
      updated_at = timezone('utc', now())
  where id = v_batch.id;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id, details)
  values (
    null, 'stripe_transfer_reversed', 'market_payout_item', v_item.id::text,
    jsonb_build_object(
      'reversal_id', input_reversal_id,
      'event_id', input_event_id,
      'amount_yen', input_reversed_yen,
      'purchase_id', v_item.purchase_id
    )
  );
end;
$$;

revoke all on function public.market_record_stripe_transfer_reversal_v1(bigint, integer, text, text)
  from public, anon, authenticated;
grant execute on function public.market_record_stripe_transfer_reversal_v1(bigint, integer, text, text)
  to service_role;

-- If a dispute is won after an earlier transfer reversal, make the reversed
-- amount payable again. Historical payout rows remain unchanged for audit.
create or replace function public.market_reopen_won_dispute_payout_v1(
  input_purchase_id uuid
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.role() <> 'service_role' then
    raise exception 'service role required';
  end if;
  update public.market_royalty_ledger ledger
  set paid_microyen = greatest(0, ledger.paid_microyen - reversals.reversed_microyen),
      status = 'pending',
      available_at = timezone('utc', now()) + interval '30 days',
      reversed_at = null
  from (
    select royalty_ledger_id, sum(reversed_microyen)::bigint as reversed_microyen
    from public.market_payout_items
    where purchase_id = input_purchase_id and reversed_microyen > 0
    group by royalty_ledger_id
  ) reversals
  where ledger.id = reversals.royalty_ledger_id
    and ledger.purchase_id = input_purchase_id;
end;
$$;

revoke all on function public.market_reopen_won_dispute_payout_v1(uuid)
  from public, anon, authenticated;
grant execute on function public.market_reopen_won_dispute_payout_v1(uuid)
  to service_role;
