create table if not exists public.browser_adfree_purchase_orders (
  id bigint generated by default as identity primary key,
  provider text not null default 'stores',
  provider_order_id text not null,
  product_key text not null default 'browser_ad_free',
  buyer_email text not null,
  payment_status text not null default 'pending',
  code text references public.user_entitlement_codes(code) on delete set null,
  issued_at timestamptz,
  claimed_at timestamptz,
  claimed_by uuid references auth.users(id) on delete set null,
  raw_payload jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (provider, provider_order_id, product_key)
);

alter table public.browser_adfree_purchase_orders
  add column if not exists provider text not null default 'stores',
  add column if not exists provider_order_id text not null default '',
  add column if not exists product_key text not null default 'browser_ad_free',
  add column if not exists buyer_email text not null default '',
  add column if not exists payment_status text not null default 'pending',
  add column if not exists code text references public.user_entitlement_codes(code) on delete set null,
  add column if not exists issued_at timestamptz,
  add column if not exists claimed_at timestamptz,
  add column if not exists claimed_by uuid references auth.users(id) on delete set null,
  add column if not exists raw_payload jsonb not null default '{}'::jsonb,
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists created_at timestamptz not null default timezone('utc', now()),
  add column if not exists updated_at timestamptz not null default timezone('utc', now());

create index if not exists browser_adfree_purchase_orders_lookup_idx
  on public.browser_adfree_purchase_orders (provider, provider_order_id, product_key);

create index if not exists browser_adfree_purchase_orders_buyer_email_idx
  on public.browser_adfree_purchase_orders (buyer_email);

create or replace function public.set_browser_adfree_purchase_orders_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists trg_set_browser_adfree_purchase_orders_updated_at on public.browser_adfree_purchase_orders;
create trigger trg_set_browser_adfree_purchase_orders_updated_at
before update on public.browser_adfree_purchase_orders
for each row
execute function public.set_browser_adfree_purchase_orders_updated_at();

alter table public.browser_adfree_purchase_orders enable row level security;

revoke all on public.browser_adfree_purchase_orders from anon, authenticated;

create or replace function public.redeem_browser_adfree_code(input_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_user_email text := lower(trim(coalesce(auth.jwt() ->> 'email', '')));
  v_code text := regexp_replace(upper(trim(coalesce(input_code, ''))), '[^A-Z0-9]', '', 'g');
  v_now timestamptz := timezone('utc', now());
  v_code_row public.user_entitlement_codes%rowtype;
  v_entitlement public.user_entitlements%rowtype;
  v_next_expires_at timestamptz := null;
  v_reserved_email text := '';
begin
  if v_user_id is null then
    raise exception 'login required';
  end if;

  if v_code = '' then
    raise exception 'code is required';
  end if;

  select *
    into v_code_row
    from public.user_entitlement_codes
   where code = v_code
   for update;

  if not found then
    raise exception 'code not found';
  end if;

  if not coalesce(v_code_row.active, false) then
    raise exception 'code inactive';
  end if;

  if v_code_row.expires_at is not null and v_code_row.expires_at <= v_now then
    raise exception 'code expired';
  end if;

  if coalesce(v_code_row.redemption_count, 0) >= coalesce(v_code_row.max_redemptions, 1) then
    raise exception 'code already redeemed';
  end if;

  v_reserved_email := lower(trim(coalesce(v_code_row.metadata ->> 'buyer_email', '')));
  if v_reserved_email <> '' and v_reserved_email <> v_user_email then
    raise exception 'purchase email mismatch';
  end if;

  select *
    into v_entitlement
    from public.user_entitlements
   where user_id = v_user_id
     and entitlement_key = v_code_row.entitlement_key
   for update;

  if found and v_entitlement.revoked_at is null and v_entitlement.status = 'active' and v_entitlement.expires_at is null then
    v_next_expires_at := null;
  else
    v_next_expires_at := greatest(coalesce(v_entitlement.expires_at, v_now), v_now)
      + make_interval(days => greatest(coalesce(v_code_row.duration_days, 31), 1));
  end if;

  insert into public.user_entitlements (
    user_id,
    entitlement_key,
    status,
    source,
    expires_at,
    granted_at,
    redeemed_code,
    metadata,
    revoked_at
  )
  values (
    v_user_id,
    v_code_row.entitlement_key,
    'active',
    'code',
    v_next_expires_at,
    v_now,
    v_code,
    jsonb_build_object(
      'last_redeemed_code', v_code,
      'last_redeemed_at', v_now
    ),
    null
  )
  on conflict (user_id, entitlement_key)
  do update set
    status = 'active',
    source = 'code',
    expires_at = excluded.expires_at,
    granted_at = excluded.granted_at,
    redeemed_code = excluded.redeemed_code,
    metadata = coalesce(public.user_entitlements.metadata, '{}'::jsonb) || excluded.metadata,
    revoked_at = null,
    updated_at = v_now;

  update public.user_entitlement_codes
     set redemption_count = coalesce(redemption_count, 0) + 1,
         redeemed_by = v_user_id,
         redeemed_at = v_now,
         updated_at = v_now
   where code = v_code;

  return jsonb_build_object(
    'ok', true,
    'entitlement_key', v_code_row.entitlement_key,
    'expires_at', v_next_expires_at,
    'redeemed_code', v_code
  );
end;
$$;

create or replace function public.claim_browser_adfree_purchase_code(input_order_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_user_email text := lower(trim(coalesce(auth.jwt() ->> 'email', '')));
  v_order_id text := upper(regexp_replace(trim(coalesce(input_order_id, '')), '\s+', '', 'g'));
  v_purchase public.browser_adfree_purchase_orders%rowtype;
  v_code_row public.user_entitlement_codes%rowtype;
begin
  if v_user_id is null then
    raise exception 'login required';
  end if;

  if v_user_email = '' then
    raise exception 'login email unavailable';
  end if;

  if v_order_id = '' then
    raise exception 'order id is required';
  end if;

  select *
    into v_purchase
    from public.browser_adfree_purchase_orders
   where product_key = 'browser_ad_free'
     and upper(regexp_replace(coalesce(provider_order_id, ''), '\s+', '', 'g')) = v_order_id
     and lower(trim(coalesce(buyer_email, ''))) = v_user_email
     and lower(trim(coalesce(payment_status, ''))) = any (array['paid', 'completed', 'confirmed', 'fulfilled'])
   order by issued_at desc nulls last, created_at desc
   limit 1
   for update;

  if not found or coalesce(v_purchase.code, '') = '' then
    raise exception 'purchase not found';
  end if;

  select *
    into v_code_row
    from public.user_entitlement_codes
   where code = v_purchase.code
   limit 1;

  if not found or not coalesce(v_code_row.active, false) then
    raise exception 'code unavailable';
  end if;

  update public.browser_adfree_purchase_orders
     set claimed_at = coalesce(claimed_at, timezone('utc', now())),
         claimed_by = coalesce(claimed_by, v_user_id),
         updated_at = timezone('utc', now())
   where id = v_purchase.id;

  return jsonb_build_object(
    'ok', true,
    'code', v_purchase.code,
    'order_id', v_purchase.provider_order_id,
    'entitlement_key', v_code_row.entitlement_key,
    'code_expires_at', v_code_row.expires_at
  );
end;
$$;

grant execute on function public.claim_browser_adfree_purchase_code(text) to authenticated;
