-- Harden the inheritance market before its first remote deployment.
-- Authentication, seller identity, listing review, and file provenance are
-- deliberately separate signals. None of them alone guarantees copyright.

create table if not exists public.market_asset_formats (
  id text primary key,
  label text not null,
  media_kind text not null check (media_kind in ('project', 'image', 'animation')),
  allows_pixieed_native boolean not null default false,
  allows_external_upload boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now())
);

insert into public.market_asset_formats (
  id, label, media_kind, allows_pixieed_native, allows_external_upload
) values
  ('pixiedraw-project', 'PiXiEEDrawプロジェクト', 'project', true, false),
  ('png', 'PNG画像', 'image', true, true),
  ('webp', 'WebP画像', 'image', true, true),
  ('gif', 'GIFアニメーション', 'animation', true, true),
  ('apng', 'APNGアニメーション', 'animation', true, true),
  ('sprite-sheet-png', 'PNGスプライトシート', 'animation', true, true)
on conflict (id) do update set
  label = excluded.label,
  media_kind = excluded.media_kind,
  allows_pixieed_native = excluded.allows_pixieed_native,
  allows_external_upload = excluded.allows_external_upload;

alter table public.market_asset_formats enable row level security;
create policy market_asset_formats_read_active
on public.market_asset_formats for select
to anon, authenticated
using (active);

create table if not exists public.market_seller_profiles (
  user_id uuid primary key references auth.users(id) on delete restrict,
  seller_status text not null default 'pending'
    check (seller_status in ('pending', 'verified', 'restricted', 'disabled')),
  identity_status text not null default 'unverified'
    check (identity_status in ('unverified', 'pending', 'verified', 'failed', 'expired')),
  terms_version text,
  terms_accepted_at timestamptz,
  verified_at timestamptz,
  restricted_reason text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (
    seller_status <> 'verified'
    or (identity_status = 'verified' and terms_accepted_at is not null)
  )
);

alter table public.market_seller_profiles enable row level security;
create policy market_seller_profiles_read_own
on public.market_seller_profiles for select
to authenticated
using (user_id = auth.uid());

create table if not exists public.market_staff_roles (
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('reviewer', 'admin')),
  active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (user_id, role)
);

alter table public.market_staff_roles enable row level security;

create table if not exists public.market_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  target_type text not null,
  target_id text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  check (jsonb_typeof(details) = 'object')
);

alter table public.market_audit_log enable row level security;
create index if not exists market_audit_log_target_idx
  on public.market_audit_log(target_type, target_id, created_at desc);

alter table public.market_assets
  add column if not exists source_kind text not null default 'external',
  add column if not exists source_sha256 text,
  add column if not exists provenance_manifest jsonb not null default '{}'::jsonb,
  add column if not exists verification_status text not null default 'pending',
  add column if not exists verification_level text not null default 'unverified',
  add column if not exists file_scan_status text not null default 'pending',
  add column if not exists seller_identity_verified boolean not null default false,
  add column if not exists verified_at timestamptz,
  add column if not exists verified_by uuid references auth.users(id) on delete set null;

alter table public.market_assets
  add constraint market_assets_source_kind_check
    check (source_kind in ('pixieed-native', 'external')),
  add constraint market_assets_source_sha256_check
    check (source_sha256 is null or source_sha256 ~ '^[0-9a-f]{64}$'),
  add constraint market_assets_provenance_manifest_check
    check (jsonb_typeof(provenance_manifest) = 'object'),
  add constraint market_assets_verification_status_check
    check (verification_status in ('pending', 'verified', 'rejected', 'revoked')),
  add constraint market_assets_verification_level_check
    check (verification_level in ('unverified', 'pixieed-native', 'external-reviewed')),
  add constraint market_assets_file_scan_status_check
    check (file_scan_status in ('pending', 'clean', 'rejected', 'error')),
  add constraint market_assets_format_fk
    foreign key (asset_format) references public.market_asset_formats(id) on delete restrict;

create or replace function public.market_current_user_has_confirmed_identity()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    auth.uid() is not null
    and lower(coalesce(auth.jwt() ->> 'is_anonymous', 'false')) not in ('true', 't', '1')
    and coalesce(auth.jwt() -> 'app_metadata' ->> 'provider', '') <> 'anonymous'
    and exists (
      select 1
      from auth.users as users
      where users.id = auth.uid()
        and users.email_confirmed_at is not null
    );
$$;

create or replace function public.market_current_user_can_sell()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.market_current_user_has_confirmed_identity()
    and exists (
      select 1
      from public.market_seller_profiles as seller
      where seller.user_id = auth.uid()
        and seller.seller_status = 'verified'
        and seller.identity_status = 'verified'
        and seller.terms_accepted_at is not null
    );
$$;

create or replace function public.market_current_user_is_reviewer()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.market_staff_roles as staff
    where staff.user_id = auth.uid()
      and staff.active
      and staff.role in ('reviewer', 'admin')
  );
$$;

revoke all on function public.market_current_user_has_confirmed_identity() from public, anon, authenticated;
revoke all on function public.market_current_user_can_sell() from public, anon, authenticated;
revoke all on function public.market_current_user_is_reviewer() from public, anon, authenticated;
grant execute on function public.market_current_user_has_confirmed_identity() to authenticated;
grant execute on function public.market_current_user_can_sell() to authenticated;
grant execute on function public.market_current_user_is_reviewer() to authenticated;

-- The v1 draft RPCs were created before seller verification existed. Keep the
-- functions for migration compatibility, but remove browser access.
revoke all on function public.market_create_root_asset(text, text, integer, integer, integer, integer, boolean, jsonb, jsonb, jsonb, text, jsonb)
  from public, anon, authenticated;
revoke all on function public.market_create_derivative_draft(uuid, uuid, text, text, integer, text, jsonb)
  from public, anon, authenticated;

create or replace function public.market_create_root_asset_v2(
  input_title text,
  input_description text,
  input_sale_price_yen integer,
  input_base_use_price_yen integer,
  input_required_option_price_yen integer,
  input_derivative_license_price_yen integer,
  input_derivative_sales_allowed boolean,
  input_source_kind text,
  input_source_sha256 text,
  input_asset_format text,
  input_provenance_manifest jsonb default '{}'::jsonb,
  input_inherited_terms jsonb default '{}'::jsonb,
  input_prohibited_uses jsonb default '[]'::jsonb,
  input_allowed_media jsonb default '[]'::jsonb,
  input_change_summary jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_asset_id uuid;
  v_format public.market_asset_formats%rowtype;
begin
  if not public.market_current_user_can_sell() then
    raise exception 'verified seller account required';
  end if;
  if input_source_kind not in ('pixieed-native', 'external') then
    raise exception 'unsupported source kind';
  end if;
  if coalesce(lower(input_source_sha256), '') !~ '^[0-9a-f]{64}$' then
    raise exception 'valid source sha256 required';
  end if;
  if jsonb_typeof(coalesce(input_provenance_manifest, '{}'::jsonb)) <> 'object' then
    raise exception 'invalid provenance manifest';
  end if;

  select * into v_format
  from public.market_asset_formats
  where id = input_asset_format and active;
  if not found
     or (input_source_kind = 'pixieed-native' and not v_format.allows_pixieed_native)
     or (input_source_kind = 'external' and not v_format.allows_external_upload) then
    raise exception 'asset format is not allowed for this source';
  end if;
  if input_source_kind = 'pixieed-native'
     and coalesce(input_provenance_manifest ->> 'schema', '') <> 'pixieed-market-manifest/v1' then
    raise exception 'PiXiEED native source requires a v1 provenance manifest';
  end if;

  v_asset_id := public.market_create_root_asset(
    input_title, input_description, input_sale_price_yen,
    input_base_use_price_yen, input_required_option_price_yen,
    input_derivative_license_price_yen, input_derivative_sales_allowed,
    input_inherited_terms, input_prohibited_uses, input_allowed_media,
    input_asset_format, input_change_summary
  );

  update public.market_assets
  set source_kind = input_source_kind,
      source_sha256 = lower(input_source_sha256),
      provenance_manifest = coalesce(input_provenance_manifest, '{}'::jsonb),
      verification_status = 'pending',
      verification_level = 'unverified',
      file_scan_status = 'pending'
  where id = v_asset_id;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id)
  values (auth.uid(), 'root_draft_created', 'market_asset', v_asset_id::text);
  return v_asset_id;
end;
$$;

create or replace function public.market_create_derivative_draft_v2(
  input_source_asset_id uuid,
  input_derivative_license_id uuid,
  input_title text,
  input_description text,
  input_sale_price_yen integer,
  input_source_kind text,
  input_source_sha256 text,
  input_asset_format text,
  input_provenance_manifest jsonb default '{}'::jsonb,
  input_change_summary jsonb default '[]'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_asset_id uuid;
  v_format public.market_asset_formats%rowtype;
begin
  if not public.market_current_user_can_sell() then
    raise exception 'verified seller account required';
  end if;
  if input_source_kind not in ('pixieed-native', 'external') then
    raise exception 'unsupported source kind';
  end if;
  if coalesce(lower(input_source_sha256), '') !~ '^[0-9a-f]{64}$' then
    raise exception 'valid source sha256 required';
  end if;
  select * into v_format
  from public.market_asset_formats
  where id = input_asset_format and active;
  if not found
     or (input_source_kind = 'pixieed-native' and not v_format.allows_pixieed_native)
     or (input_source_kind = 'external' and not v_format.allows_external_upload) then
    raise exception 'asset format is not allowed for this source';
  end if;
  if input_source_kind = 'pixieed-native'
     and coalesce(input_provenance_manifest ->> 'schema', '') <> 'pixieed-market-manifest/v1' then
    raise exception 'PiXiEED native source requires a v1 provenance manifest';
  end if;

  v_asset_id := public.market_create_derivative_draft(
    input_source_asset_id, input_derivative_license_id, input_title,
    input_description, input_sale_price_yen, input_asset_format,
    input_change_summary
  );

  update public.market_assets
  set source_kind = input_source_kind,
      source_sha256 = lower(input_source_sha256),
      provenance_manifest = coalesce(input_provenance_manifest, '{}'::jsonb),
      verification_status = 'pending',
      verification_level = 'unverified',
      file_scan_status = 'pending'
  where id = v_asset_id;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id)
  values (auth.uid(), 'derivative_draft_created', 'market_asset', v_asset_id::text);
  return v_asset_id;
end;
$$;

grant execute on function public.market_create_root_asset_v2(text, text, integer, integer, integer, integer, boolean, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb)
  to authenticated;
grant execute on function public.market_create_derivative_draft_v2(uuid, uuid, text, text, integer, text, text, text, jsonb, jsonb)
  to authenticated;

create or replace function public.market_review_listing(
  input_asset_id uuid,
  input_decision text,
  input_reason text default ''
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_asset public.market_assets%rowtype;
  v_seller public.market_seller_profiles%rowtype;
begin
  if not public.market_current_user_is_reviewer() then
    raise exception 'reviewer permission required';
  end if;
  if input_decision not in ('approved', 'rejected', 'suspended') then
    raise exception 'invalid review decision';
  end if;

  select * into v_asset from public.market_assets where id = input_asset_id for update;
  if not found then
    raise exception 'asset not found';
  end if;
  select * into v_seller
  from public.market_seller_profiles
  where user_id = v_asset.creator_user_id;

  if input_decision = 'approved' then
    if not found
       or v_seller.seller_status <> 'verified'
       or v_seller.identity_status <> 'verified' then
      raise exception 'seller identity is not verified';
    end if;
    if v_asset.source_sha256 is null or v_asset.file_scan_status <> 'clean' then
      raise exception 'clean verified source file required';
    end if;
    update public.market_assets
    set status = 'published',
        verification_status = 'verified',
        verification_level = case
          when source_kind = 'pixieed-native' then 'pixieed-native'
          else 'external-reviewed'
        end,
        seller_identity_verified = true,
        verified_at = timezone('utc', now()),
        verified_by = auth.uid(),
        published_at = coalesce(published_at, timezone('utc', now()))
    where id = input_asset_id;
    update public.market_asset_series
    set status = 'published', updated_at = timezone('utc', now())
    where root_asset_id = input_asset_id;
  elsif input_decision = 'rejected' then
    update public.market_assets
    set status = 'rejected', verification_status = 'rejected',
        verified_at = timezone('utc', now()), verified_by = auth.uid()
    where id = input_asset_id;
  else
    update public.market_assets
    set status = 'suspended', verification_status = 'revoked',
        seller_identity_verified = false,
        verified_at = timezone('utc', now()), verified_by = auth.uid()
    where id = input_asset_id;
  end if;

  insert into public.market_listing_reviews(asset_id, reviewer_user_id, decision, reason)
  values (input_asset_id, auth.uid(), input_decision, coalesce(input_reason, ''));
  insert into public.market_audit_log(actor_user_id, action, target_type, target_id, details)
  values (
    auth.uid(), 'listing_reviewed', 'market_asset', input_asset_id::text,
    jsonb_build_object('decision', input_decision, 'reason', coalesce(input_reason, ''))
  );
end;
$$;

grant execute on function public.market_review_listing(uuid, text, text) to authenticated;
