-- Monthly display-reward allocations are not sales and must remain separately
-- auditable. They do, however, share the creator's one Stripe payout request.

alter table public.market_pageview_reward_allocations
  add column if not exists paid_microyen bigint not null default 0;

alter table public.market_pageview_reward_allocations
  drop constraint if exists market_pageview_reward_allocations_paid_microyen_check;
alter table public.market_pageview_reward_allocations
  add constraint market_pageview_reward_allocations_paid_microyen_check
  check (paid_microyen >= 0 and paid_microyen <= amount_microyen);

create table if not exists public.market_pageview_reward_payout_items (
  id bigint generated by default as identity primary key,
  batch_id uuid not null references public.market_payout_batches(id) on delete restrict,
  reward_year integer not null,
  reward_month integer not null,
  source_asset_id uuid not null,
  recipient_asset_id uuid not null,
  amount_microyen bigint not null check (amount_microyen > 0),
  created_at timestamptz not null default timezone('utc', now()),
  unique (batch_id, reward_year, reward_month, source_asset_id, recipient_asset_id),
  foreign key (reward_year, reward_month, source_asset_id, recipient_asset_id)
    references public.market_pageview_reward_allocations(
      reward_year, reward_month, source_asset_id, recipient_asset_id
    ) on delete restrict
);

create index if not exists market_pageview_reward_payout_items_allocation_idx
  on public.market_pageview_reward_payout_items(
    reward_year, reward_month, source_asset_id, recipient_asset_id
  );

alter table public.market_pageview_reward_payout_items enable row level security;
revoke all on public.market_pageview_reward_payout_items from public, anon, authenticated;
create policy market_pageview_reward_payout_items_read_own
on public.market_pageview_reward_payout_items for select to authenticated
using (
  exists (
    select 1 from public.market_payout_batches batch
    where batch.id = batch_id and batch.recipient_user_id = auth.uid()
  )
);

-- A finalized display-reward month is immediately available. Unlike a sale,
-- this amount is funded from the already-set monthly PiXiEED reward budget and
-- has no purchaser refund window.
create or replace function public.market_quote_stripe_payout_v1()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_total_microyen bigint;
  v_gross_yen integer;
  v_account_ready boolean;
  v_quote jsonb;
begin
  if v_user_id is null then raise exception 'login required'; end if;
  update public.market_royalty_ledger set status = 'available'
  where recipient_user_id = v_user_id and status = 'pending'
    and available_at <= timezone('utc', now()) and paid_microyen < amount_microyen;

  select coalesce(sum(balance.amount_microyen), 0)::bigint into v_total_microyen
  from (
    select ledger.amount_microyen - ledger.paid_microyen as amount_microyen
    from public.market_royalty_ledger ledger
    where ledger.recipient_user_id = v_user_id
      and ledger.status = 'available'
      and ledger.paid_microyen < ledger.amount_microyen
    union all
    select allocation.amount_microyen - allocation.paid_microyen
    from public.market_pageview_reward_allocations allocation
    join public.market_pageview_reward_runs run
      using (reward_year, reward_month)
    where allocation.recipient_user_id = v_user_id
      and run.status = 'finalized'
      and allocation.paid_microyen < allocation.amount_microyen
  ) balance;
  v_gross_yen := floor(v_total_microyen::numeric / 1000000)::integer;
  select exists (
    select 1 from public.market_seller_payout_accounts
    where user_id = v_user_id and provider = 'stripe'
      and onboarding_status = 'verified' and payouts_enabled
  ) into v_account_ready;
  v_quote := case when v_gross_yen > 0 then public.market_stripe_payout_fee_quote_v1(v_gross_yen) else '{}'::jsonb end;
  return v_quote || jsonb_build_object(
    'minimum_yen', 5000, 'eligible', v_gross_yen >= 5000 and v_account_ready,
    'stripe_ready', v_account_ready
  );
end;
$$;

create or replace function public.market_request_stripe_payout_v1(
  input_minimum_yen integer default 5000
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_total_microyen bigint;
  v_gross_yen integer;
  v_quote jsonb;
  v_account_id text;
  v_request public.market_payout_requests%rowtype;
  v_month date := date_trunc('month', timezone('Asia/Tokyo', now()))::date;
begin
  if v_user_id is null then raise exception 'login required'; end if;
  if input_minimum_yen < 1 or input_minimum_yen > 10000000 then raise exception 'invalid payout minimum'; end if;

  update public.market_royalty_ledger set status = 'available'
  where recipient_user_id = v_user_id and status = 'pending'
    and available_at <= timezone('utc', now()) and paid_microyen < amount_microyen;

  select provider_account_id into v_account_id
  from public.market_seller_payout_accounts
  where user_id = v_user_id and provider = 'stripe'
    and onboarding_status = 'verified' and payouts_enabled;
  if coalesce(v_account_id, '') = '' then
    raise exception 'Stripeの売上受取設定を完了してください';
  end if;

  select coalesce(sum(balance.amount_microyen), 0)::bigint into v_total_microyen
  from (
    select ledger.amount_microyen - ledger.paid_microyen as amount_microyen
    from public.market_royalty_ledger ledger
    where ledger.recipient_user_id = v_user_id and ledger.status = 'available'
      and ledger.paid_microyen < ledger.amount_microyen
    union all
    select allocation.amount_microyen - allocation.paid_microyen
    from public.market_pageview_reward_allocations allocation
    join public.market_pageview_reward_runs run using (reward_year, reward_month)
    where allocation.recipient_user_id = v_user_id and run.status = 'finalized'
      and allocation.paid_microyen < allocation.amount_microyen
  ) balance;
  if v_total_microyen < input_minimum_yen::bigint * 1000000 then
    raise exception '確定済み残高が出金最低額に達していません';
  end if;
  v_gross_yen := floor(v_total_microyen::numeric / 1000000)::integer;
  v_quote := public.market_stripe_payout_fee_quote_v1(v_gross_yen);
  if coalesce((v_quote ->> 'transfer_amount_yen')::integer, 0) < 1 then
    raise exception 'Stripe費用を差し引くと送金額が残りません';
  end if;

  insert into public.market_payout_requests (
    recipient_user_id, request_month, minimum_yen, requested_amount_yen,
    provider_fee_yen, transfer_amount_yen, fee_quote
  ) values (
    v_user_id, v_month, input_minimum_yen, v_gross_yen,
    (v_quote ->> 'provider_fee_yen')::integer, (v_quote ->> 'transfer_amount_yen')::integer, v_quote
  ) returning * into v_request;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id, details)
  values (v_user_id, 'stripe_payout_requested', 'market_payout_request', v_request.id::text,
    jsonb_build_object('minimum_yen', input_minimum_yen, 'requested_amount_yen', v_request.requested_amount_yen, 'provider_fee_yen', v_request.provider_fee_yen, 'transfer_amount_yen', v_request.transfer_amount_yen, 'includes_pageview_rewards', true));

  return jsonb_build_object('request_id', v_request.id, 'amount_yen', v_request.transfer_amount_yen, 'gross_amount_yen', v_request.requested_amount_yen, 'provider_fee_yen', v_request.provider_fee_yen, 'fee_quote', v_request.fee_quote);
exception when unique_violation then
  raise exception '今月の出金申請はすでに処理中または完了しています';
end;
$$;

create or replace function public.market_prepare_requested_stripe_payout_v1(
  input_request_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.market_payout_requests%rowtype;
  v_batch public.market_payout_batches%rowtype;
  v_account_id text;
  v_total_microyen bigint;
  v_allocation_microyen bigint;
  v_remaining bigint;
  v_ledger record;
  v_pageview record;
  v_allocation bigint;
begin
  if auth.role() <> 'service_role' then raise exception 'service role required'; end if;

  select * into v_request from public.market_payout_requests
  where id = input_request_id for update;
  if not found then raise exception 'payout request not found'; end if;
  if v_request.status <> 'requested' then raise exception 'payout request is not pending'; end if;

  select provider_account_id into v_account_id
  from public.market_seller_payout_accounts
  where user_id = v_request.recipient_user_id and provider = 'stripe'
    and onboarding_status = 'verified' and payouts_enabled;
  if coalesce(v_account_id, '') = '' then raise exception 'Stripe payout account is not ready'; end if;

  select coalesce(sum(balance.amount_microyen), 0)::bigint into v_total_microyen
  from (
    select ledger.amount_microyen - ledger.paid_microyen as amount_microyen
    from public.market_royalty_ledger ledger
    where ledger.recipient_user_id = v_request.recipient_user_id and ledger.status = 'available'
      and ledger.paid_microyen < ledger.amount_microyen
    union all
    select allocation.amount_microyen - allocation.paid_microyen
    from public.market_pageview_reward_allocations allocation
    join public.market_pageview_reward_runs run using (reward_year, reward_month)
    where allocation.recipient_user_id = v_request.recipient_user_id and run.status = 'finalized'
      and allocation.paid_microyen < allocation.amount_microyen
  ) balance;
  if v_total_microyen < v_request.requested_amount_yen::bigint * 1000000 then
    raise exception 'payout balance is below minimum';
  end if;

  v_allocation_microyen := v_request.requested_amount_yen::bigint * 1000000;
  insert into public.market_payout_batches (
    recipient_user_id, provider_account_id, amount_yen, amount_microyen
  ) values (
    v_request.recipient_user_id, v_account_id,
    v_request.transfer_amount_yen, v_request.transfer_amount_yen::bigint * 1000000
  ) returning * into v_batch;

  v_remaining := v_allocation_microyen;
  for v_ledger in
    select id, purchase_id, amount_microyen, paid_microyen
    from public.market_royalty_ledger
    where recipient_user_id = v_request.recipient_user_id and status = 'available'
      and paid_microyen < amount_microyen
    order by available_at, created_at, id for update
  loop
    exit when v_remaining <= 0;
    v_allocation := least(v_remaining, v_ledger.amount_microyen - v_ledger.paid_microyen);
    insert into public.market_payout_items(batch_id, royalty_ledger_id, purchase_id, amount_microyen)
    values (v_batch.id, v_ledger.id, v_ledger.purchase_id, v_allocation);
    v_remaining := v_remaining - v_allocation;
  end loop;

  for v_pageview in
    select allocation.reward_year, allocation.reward_month, allocation.source_asset_id,
      allocation.recipient_asset_id, allocation.amount_microyen, allocation.paid_microyen
    from public.market_pageview_reward_allocations allocation
    join public.market_pageview_reward_runs run using (reward_year, reward_month)
    where allocation.recipient_user_id = v_request.recipient_user_id and run.status = 'finalized'
      and allocation.paid_microyen < allocation.amount_microyen
    order by run.finalized_at, allocation.reward_year, allocation.reward_month,
      allocation.source_asset_id, allocation.recipient_asset_id
    for update of allocation
  loop
    exit when v_remaining <= 0;
    v_allocation := least(v_remaining, v_pageview.amount_microyen - v_pageview.paid_microyen);
    insert into public.market_pageview_reward_payout_items(
      batch_id, reward_year, reward_month, source_asset_id, recipient_asset_id, amount_microyen
    ) values (
      v_batch.id, v_pageview.reward_year, v_pageview.reward_month,
      v_pageview.source_asset_id, v_pageview.recipient_asset_id, v_allocation
    );
    v_remaining := v_remaining - v_allocation;
  end loop;
  if v_remaining <> 0 then raise exception 'payout allocation did not balance'; end if;

  update public.market_payout_requests
  set status = 'processing', payout_batch_id = v_batch.id, updated_at = timezone('utc', now())
  where id = v_request.id;

  return jsonb_build_object('batch_id', v_batch.id, 'provider_account_id', v_account_id,
    'amount_yen', v_batch.amount_yen, 'gross_amount_yen', v_request.requested_amount_yen,
    'provider_fee_yen', v_request.provider_fee_yen, 'fee_quote', v_request.fee_quote, 'currency', v_batch.currency);
end;
$$;

create or replace function public.market_finalize_stripe_payout_batch_v1(
  input_batch_id uuid,
  input_transfer_id text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_batch public.market_payout_batches%rowtype;
begin
  if auth.role() <> 'service_role' then raise exception 'service role required'; end if;
  select * into v_batch from public.market_payout_batches
  where id = input_batch_id for update;
  if not found then raise exception 'payout batch not found'; end if;
  if v_batch.status = 'transferred' and v_batch.provider_transfer_id = btrim(input_transfer_id) then return; end if;
  if v_batch.status <> 'prepared' then raise exception 'payout batch is not prepared'; end if;

  update public.market_royalty_ledger ledger
  set paid_microyen = ledger.paid_microyen + allocations.amount_microyen,
      status = case when ledger.paid_microyen + allocations.amount_microyen >= ledger.amount_microyen then 'paid_out' else 'available' end
  from (
    select royalty_ledger_id, sum(amount_microyen)::bigint as amount_microyen
    from public.market_payout_items where batch_id = input_batch_id group by royalty_ledger_id
  ) allocations
  where ledger.id = allocations.royalty_ledger_id;

  update public.market_pageview_reward_allocations allocation
  set paid_microyen = allocation.paid_microyen + items.amount_microyen
  from (
    select reward_year, reward_month, source_asset_id, recipient_asset_id,
      sum(amount_microyen)::bigint as amount_microyen
    from public.market_pageview_reward_payout_items
    where batch_id = input_batch_id
    group by reward_year, reward_month, source_asset_id, recipient_asset_id
  ) items
  where allocation.reward_year = items.reward_year
    and allocation.reward_month = items.reward_month
    and allocation.source_asset_id = items.source_asset_id
    and allocation.recipient_asset_id = items.recipient_asset_id;

  update public.market_payout_batches
  set status = 'transferred', provider_transfer_id = btrim(input_transfer_id),
      transferred_at = timezone('utc', now()), updated_at = timezone('utc', now())
  where id = input_batch_id;

  insert into public.market_audit_log(actor_user_id, action, target_type, target_id, details)
  values (null, 'stripe_payout_transferred', 'market_payout_batch', input_batch_id::text,
    jsonb_build_object('transfer_id', input_transfer_id, 'amount_yen', v_batch.amount_yen,
      'includes_pageview_rewards', exists(select 1 from public.market_pageview_reward_payout_items where batch_id = input_batch_id)));
end;
$$;

create or replace function public.market_my_reward_dashboard_v1(
  input_months integer default 12
)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_months integer := least(24, greatest(6, coalesce(input_months, 12)));
  v_user_id uuid := auth.uid();
  v_result jsonb;
begin
  if v_user_id is null then raise exception 'login required'; end if;

  with month_axis as (
    select generate_series(
      date_trunc('month', timezone('Asia/Tokyo', now()))::date - ((v_months - 1) * interval '1 month'),
      date_trunc('month', timezone('Asia/Tokyo', now()))::date, interval '1 month'
    )::date as month_start
  ), ledger_monthly as (
    select date_trunc('month', timezone('Asia/Tokyo', coalesce(purchase.paid_at, ledger.created_at)))::date as month_start,
      coalesce(sum(ledger.amount_microyen) filter (where ledger.lineage_depth = 0), 0)::bigint as sales_microyen,
      coalesce(sum(ledger.amount_microyen) filter (where ledger.lineage_depth > 0), 0)::bigint as lineage_microyen,
      count(distinct ledger.purchase_id) filter (where ledger.lineage_depth = 0)::bigint as sale_count,
      count(distinct ledger.purchase_id) filter (where ledger.lineage_depth > 0)::bigint as lineage_sale_count
    from public.market_royalty_ledger ledger join public.market_purchases purchase on purchase.id = ledger.purchase_id
    where ledger.recipient_user_id = v_user_id and ledger.status <> 'reversed'
      and coalesce(purchase.paid_at, ledger.created_at) >= (select min(month_start) from month_axis)
    group by 1
  ), pageview_sources as (
    select make_date(allocation.reward_year, allocation.reward_month, 1) as month_start,
      allocation.source_asset_id, max(allocation.source_view_count)::bigint as valid_view_count,
      sum(allocation.amount_microyen)::bigint as pageview_microyen
    from public.market_pageview_reward_allocations allocation
    join public.market_pageview_reward_runs run using (reward_year, reward_month)
    where allocation.recipient_user_id = v_user_id and run.status = 'finalized'
      and make_date(allocation.reward_year, allocation.reward_month, 1) >= (select min(month_start) from month_axis)
    group by 1, allocation.source_asset_id
  ), pageview_monthly as (
    select month_start, sum(pageview_microyen)::bigint as pageview_microyen,
      sum(valid_view_count)::bigint as valid_view_count from pageview_sources group by month_start
  ), monthly as (
    select axis.month_start, coalesce(ledger.sales_microyen, 0)::bigint as sales_microyen,
      coalesce(ledger.lineage_microyen, 0)::bigint as lineage_microyen,
      coalesce(pageviews.pageview_microyen, 0)::bigint as pageview_microyen,
      coalesce(pageviews.valid_view_count, 0)::bigint as valid_view_count,
      coalesce(ledger.sale_count, 0)::bigint as sale_count,
      coalesce(ledger.lineage_sale_count, 0)::bigint as lineage_sale_count
    from month_axis axis left join ledger_monthly ledger using (month_start)
    left join pageview_monthly pageviews using (month_start) order by axis.month_start
  ), balances as (
    select
      coalesce(sum(balance.amount_microyen) filter (where balance.bucket = 'available'), 0)::bigint as available_microyen,
      coalesce(sum(balance.amount_microyen) filter (where balance.bucket = 'pending'), 0)::bigint as pending_microyen
    from (
      select ledger.amount_microyen - ledger.paid_microyen as amount_microyen,
        case when ledger.status = 'available' then 'available' else 'pending' end as bucket
      from public.market_royalty_ledger ledger
      where ledger.recipient_user_id = v_user_id and ledger.status in ('available', 'pending')
        and ledger.paid_microyen < ledger.amount_microyen
      union all
      select allocation.amount_microyen - allocation.paid_microyen, 'available'
      from public.market_pageview_reward_allocations allocation
      join public.market_pageview_reward_runs run using (reward_year, reward_month)
      where allocation.recipient_user_id = v_user_id and run.status = 'finalized'
        and allocation.paid_microyen < allocation.amount_microyen
    ) balance
  )
  select jsonb_build_object(
    'months', v_months, 'currency', 'jpy',
    'totals', jsonb_build_object(
      'sales_microyen', coalesce(sum(monthly.sales_microyen), 0),
      'lineage_microyen', coalesce(sum(monthly.lineage_microyen), 0),
      'pageview_microyen', coalesce(sum(monthly.pageview_microyen), 0),
      'valid_view_count', coalesce(sum(monthly.valid_view_count), 0),
      'sale_count', coalesce(sum(monthly.sale_count), 0),
      'lineage_sale_count', coalesce(sum(monthly.lineage_sale_count), 0),
      'available_microyen', (select available_microyen from balances),
      'pending_microyen', (select pending_microyen from balances)
    ),
    'series', coalesce(jsonb_agg(jsonb_build_object(
      'month', to_char(monthly.month_start, 'YYYY-MM'),
      'sales_microyen', monthly.sales_microyen, 'lineage_microyen', monthly.lineage_microyen,
      'pageview_microyen', monthly.pageview_microyen, 'valid_view_count', monthly.valid_view_count,
      'sale_count', monthly.sale_count, 'lineage_sale_count', monthly.lineage_sale_count
    ) order by monthly.month_start), '[]'::jsonb)
  ) into v_result from monthly;
  return v_result;
end;
$$;

revoke all on function public.market_quote_stripe_payout_v1() from public, anon;
grant execute on function public.market_quote_stripe_payout_v1() to authenticated;
revoke all on function public.market_request_stripe_payout_v1(integer) from public, anon;
grant execute on function public.market_request_stripe_payout_v1(integer) to authenticated;
revoke all on function public.market_prepare_requested_stripe_payout_v1(uuid) from public, anon, authenticated;
grant execute on function public.market_prepare_requested_stripe_payout_v1(uuid) to service_role;
revoke all on function public.market_finalize_stripe_payout_batch_v1(uuid, text) from public, anon, authenticated;
grant execute on function public.market_finalize_stripe_payout_batch_v1(uuid, text) to service_role;
revoke all on function public.market_my_reward_dashboard_v1(integer) from public, anon;
grant execute on function public.market_my_reward_dashboard_v1(integer) to authenticated;
